testing:
  only_detect: False
  num_classes: 54

dataset:
  name: MTSD
  num_workers: 4
  mtsd_labels: C:\Users\saibo\Documents\bachelor_project\data\classes\map_gtsdb2num.json
  test:
    batch_size: 2
    transforms:
      min_area: 0
      img_size: 


model_dir: C:\Users\saibo\Documents\bachelor_project\outputs\_saved\mtsd_detection_30_2\saved_models\model.pkl
classifier_dir: C:\Users\saibo\Documents\bachelor_project\outputs\_saved\mtsd_cls_10\saved_models\classifier.pkl

save_dir: C:\Users\saibo\Documents\bachelor_project\outputs\_saved\output
